{% set name = "pydantic-openapi-schema" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_openapi_schema-{{ version }}.tar.gz
  sha256: 50bf6ee00fc0dcd1c87b96f30c3273e3bebcc12f23f30c31e5af5ec2e3275c87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - python >=3.8
    - email-validator
    - pydantic >=1.10.0

test:
  imports:
    - pydantic_openapi_schema
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/starlite-api/pydantic-openapi-schema
  doc_url: https://starlite-api.github.io/pydantic-openapi-schema/
  summary: OpenAPI Schema using pydantic. Forked for Starlite-API from 'openapi-schema-pydantic'.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
