{% set name = "pydantic-openapi-schema" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic-openapi-schema-{{ version }}.tar.gz
  sha256: 2aed6913080f1dae94234e00d0905504c6aab65ab6afe246ed7aa98da989f69e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7
  run:
    - python >=3.7
    - email-validator
    - pydantic

test:
  imports:
    - pydantic_openapi_schema
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/starlite-api/pydantic-openapi-schema
  doc_url: https://starlite-api.github.io/pydantic-openapi-schema/
  summary: OpenAPI Schema using pydantic. Forked for Starlite-API from 'openapi-schema-pydantic'.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
